# Generated by Django 4.0.6 on 2022-09-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turnopedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('hora', models.IntegerField()),
                ('hora1', models.IntegerField()),
                ('hora2', models.IntegerField()),
                ('hora3', models.IntegerField()),
                ('hora4', models.IntegerField()),
                ('clase', models.IntegerField()),
            ],
        ),
    ]
