# Generated by Django 4.0.6 on 2023-04-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='dia',
            field=models.IntegerField(null=True),
        ),
    ]
