# Generated by Django 4.0.6 on 2023-04-09 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0002_turno_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='dia',
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Turnos.turno')),
            ],
        ),
    ]
